name: Publish DockerTools
on: 
  push: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    uses: KenbiTech/github-actions-reusable/.github/workflows/publish-package.yml@main
    with:
      use-notifications: ${{ vars.NOTIFICATIONS_RELEASE_ACTIVE }}
      package-name: DockerTools
      script-filename: publish
      project-name: DockerTools
      use-sonarqube: false
      autoversion-project-folder: './DockerTools'
    secrets: inherit
      