name: Publish DockerTools
on: 
  push: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix:
          
  publish-tools:
    uses: KenbiTech/github-actions-reusable/.github/workflows/publish-package.yml@main
    needs: [ generate-release ]
    with:
      use-notifications: ${{ vars.NOTIFICATIONS_RELEASE_ACTIVE }}
      package-name: DockerTools
      script-filename: publish
      project-name: DockerTools
      use-sonarqube: false
    secrets: inherit
      