name: Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
    - 'README.MD'
    - 'icon.png'
    - '.github/workflows/*'
    - '*.Tests*'
    - 'push*.sh'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  NOTIFICATIONS_ACTIVE: ${{ secrets.NOTIFICATIONS_PR_ACTIVE || 'true' }}
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Validate
    if: github.event.pull_request.draft == false
    env:
      AWS_REGION_TOOLING: eu-central-1
    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: AWS Code Artifact
      uses: KenbiTech/github-actions-code-artifact@v3
      with:
        aws-region: ${{ env.AWS_REGION_TOOLING }}
        aws-role: ${{ vars.AWS_TOOLING_CODEARTIFACT_ROLE }}

    - name: Build
      run: dotnet build --configuration Release	
    
    # - name: Run Tests
      # id: tests
      # run: |
         # dotnet test --configuration Release --no-build --verbosity quiet ./DockerTools.Tests.Integration 
                                                                                 
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: [validate]
    if: always() && github.event.pull_request.draft == false && vars.NOTIFICATIONS_PR_ACTIVE == 'true' && contains(needs.*.result, 'failure')
    steps:
      - name: Notify failure on Slack
        id: notify
        uses: KenbiTech/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{env.REPOSITORY_NAME}}-releases
          slack-text: Please check error on Pull Request - ${{ github.server_url }}/KenbiTech/${{ env.REPOSITORY_NAME }}/actions/runs/${{ github.run_id }}
          slack-optional-username: ${{ env.REPOSITORY_NAME }}
          slack-optional-icon_emoji: ":${{ env.REPOSITORY_NAME }}:"